### ISSUE TITLE
sync-to-bundle doesn't work for data exceeding 100 items

### ISSUE THREAD

**Issue by timqzm** [contentful/contentful-utilities.swift#13]
`SyncJSONDownloader.fetchSync` performs only 2 requests, and as a result we have `0.json` (kinda empty) and `1.json`.
But `1.json` can contain 100 items max, so the tool should go for the next bunch of data using `nextPageUrl`.
<img width="248" alt="Screenshot 2020-02-10 at 13 22 05" src="https://user-images.githubusercontent.com/13407092/74151292-85702e80-4c14-11ea-8a2a-0b822fed2ffc.png">
I think `SyncJSONDownloader.fetchSync` should have recursive calls like in `Client.sync`, not just `.fetch`es with `.sync` endpoint.

**Comment by marcin-bo** [comment]
I confirm that the issue exists - only first 100 entities from Contentful is downloaded.

**Comment by timqzm** [comment]
@marcin-bo  if you struggle with it, you can use my dirty workaround.
I modified pod and saved it in a side branch:
<img width="874" alt="Screenshot 2020-03-11 at 11 22 19" src="https://user-images.githubusercontent.com/13407092/76401479-9bdfe600-638a-11ea-8d9a-72a4153238ad.png">
Now when I do cold start on simulator, all jsons are stored at printed path

**Comment by marcin-bo** [comment]
Hi,

Thanks @timqzm for the solution.

I've created my own fix: downgraded `contentful-utilities` and its dependencies - and now it's downloading all items from Contentful.

Here's the branch with my fix:
https://github.com/marcin-bo/contentful-utilities.swift/tree/fix_download_limit

**Comment by matelo** [comment]
hello @marcin-bo, thanks for the fix. As far as I see, you have set exact dependencies version?

**Comment by matelo** [comment]
fixed in PR https://github.com/contentful/contentful-utilities.swift/pull/15

**Comment by matelo** [comment]
fixed
