### ISSUE TITLE
Dependency graph is unresolvable; found these conflicting requirements

### ISSUE THREAD

**Issue by aanchalkalani** [contentful/contentful-utilities.swift#14]
Hi

While installing in the package getting the below error:-

**error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies:
https://github.com/JohnSundell/Files @ 4.1.1..<5.0.0**

Any help will really be appreciated.

In Package file:-

.package(
url: "https://github.com/JohnSundell/Files",
.upToNextMajor(from: "4.1.1")
),

Thanks,
Aanchal

**Comment by matelo** [comment]
Hi @aanchalkalani 
Thanks for info, can you please be more specific?
I have run `make install`:
`matelo@DESKTOP-H8837T0 contentful-utilities.swift % make install
swift package update
Fetching https://github.com/contentful/contentful-persistence.swift
Fetching https://github.com/kylef/Commander
Fetching https://github.com/johnsundell/files.git
Fetching https://github.com/mxcl/PromiseKit.git
Fetching https://github.com/contentful/contentful.swift
Fetching https://github.com/kylef/Spectre.git
Completed resolution in 17.29s
Cloning https://github.com/mxcl/PromiseKit.git
Resolving https://github.com/mxcl/PromiseKit.git at 6.13.1
Cloning https://github.com/contentful/contentful-persistence.swift
Resolving https://github.com/contentful/contentful-persistence.swift at 0.15.0
Cloning https://github.com/contentful/contentful.swift
Resolving https://github.com/contentful/contentful.swift at 5.0.8
Cloning https://github.com/kylef/Commander
Resolving https://github.com/kylef/Commander at 0.9.1
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.9.0
Cloning https://github.com/johnsundell/files.git
Resolving https://github.com/johnsundell/files.git at 4.1.1
matelo@DESKTOP-H8837T0 contentful-utilities.swift % `

**Comment by matelo** [comment]
closing due inactivity
